# Generated by Django 5.1.1 on 2024-10-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('CITY_ACCOUNTANT', "CITY ACCOUNTANT'S OFFICE"), ('CITY_AGRICULTURE', 'CITY AGRICULTURE OFFICE'), ('CITY_ASSESSOR', "CITY ASSESSOR'S OFFICE"), ('CITY_BUDGET', 'CITY BUDGET OFFICE'), ('CITY_ENGINEERING', 'CITY ENGINEERING OFFICE'), ('CITY_GENERAL_SERVICES', 'CITY GENERAL SERVICES OFFICE'), ('CITY_HEALTH', 'CITY HEALTH DEPARTMENT'), ('CITY_TREASURER', "CITY TREASURER'S OFFICE"), ('CITY_DISASTER_RRM', 'CITY DISASTER RRM OFFICE'), ('ORMOC_WATERWORKS', 'ORMOC WATERWORKS OFFICE'), ('SPORTS', 'SPORTS OFFICE')], default='CITY_ACCOUNTANT', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default='12345', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='myapp.department')),
            ],
        ),
    ]
