# Generated by Django 5.1.1 on 2024-09-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]


def populate_departments(apps, schema_editor):
    Department = apps.get_model('your_app_name', 'Department')
    departments = [
        "CITY ACCOUNTANT'S OFFICE",
        "CITY AGRICULTURE OFFICE",
        "CITY ASSESSOR'S OFFICE",
        "CITY BUDGET OFFICE",
        "CITY ENGINEERING OFFICE",
        "CITY GENERAL SERVICES OFFICE",
        "CITY HEALTH DEPARTMENT",
        "CITY TREASURER'S OFFICE",
        "CITY DISASTER RRM OFFICE",
        "ORMOC WATERWORKS OFFICE",
        "SPORTS OFFICE"
    ]

    for department in departments:
        Department.objects.create(name=department)

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_departments),
    ]

