# Generated by Django 4.2.6 on 2024-10-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent_department',
        ),

    ]
