# Generated by Django 5.1.1 on 2024-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_department_name_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('CITY_ACCOUNTANT', "CITY ACCOUNTANT'S OFFICE"), ('CITY_AGRICULTURE', 'CITY AGRICULTURE OFFICE'), ('CITY_ASSESSOR', "CITY ASSESSOR'S OFFICE"), ('CITY_BUDGET', 'CITY BUDGET OFFICE'), ('CITY_ENGINEERING', 'CITY ENGINEERING OFFICE'), ('CITY_GENERAL_SERVICES', 'CITY GENERAL SERVICES OFFICE'), ('CITY_HEALTH', 'CITY HEALTH DEPARTMENT'), ('CITY_TREASURER', "CITY TREASURER'S OFFICE"), ('CITY_DISASTER_RRM', 'CITY DISASTER RRM OFFICE'), ('ORMOC_WATERWORKS', 'ORMOC WATERWORKS OFFICE'), ('SPORTS', 'SPORTS OFFICE')], default='CITY_ACCOUNTANT', max_length=100),
        ),
    ]
