# Generated by Django 5.1.1 on 2024-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_first_name_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='12345', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
